### ISSUE TITLE
Message erreur

### ISSUE THREAD

**Issue by Niakette** [IFATech-Metz/dev-log-3#29]
Lorsque la ville n'existe pas ( par exemple "hfdddf"), un message d'erreur apparaît, je ne sais pas si c'est volontaire ou pas.

**Comment by njonsss** [comment]
non c'est volontaire le faite qu'une erreur s'affiche quand il y a un probleme

**Comment by njonsss** [comment]
quand la ville n'existe pas mais je verrais ce que vous avez faite pour avoir d'autre idée
