### ISSUE TITLE
Irrespect mineur de la consigne

### ISSUE THREAD

**Issue by quenfil** [IFATech-Metz/dev-log-3#30]
Il était demandé cinq jours de prévisions et non trois. Peut ne pas être pénalisant mais ce fait est signalé au cas où.

P.S : Le Times New Roman au milieu d'une page autrement soignée, c'est dommage.

**Comment by njonsss** [comment]
non  on a regarder dans le devlog10 ou il n y a pas de jours précis demander pour les previsions
